# Generated by Django 4.1.4 on 2022-12-10 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=64)),
                ('mobile', models.CharField(max_length=20)),
                ('decp', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buyer', models.CharField(max_length=150)),
                ('Address', models.TextField(max_length=450)),
                ('PinCode', models.CharField(max_length=7)),
                ('Email', models.EmailField(max_length=150)),
                ('ProductName', models.CharField(max_length=150)),
                ('ProductQty', models.CharField(max_length=150)),
                ('ProductSize', models.CharField(max_length=150)),
                ('ProductColor', models.CharField(max_length=150)),
                ('ProductImg', models.URLField(max_length=150)),
                ('ProductPrice', models.CharField(max_length=150)),
                ('SellerEmail', models.EmailField(max_length=150)),
                ('SellerName', models.CharField(max_length=150)),
                ('SellerPhone', models.CharField(default='', max_length=15)),
                ('Phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Profile_Pic', models.ImageField(upload_to='User_Profile_pics')),
                ('Firstname', models.CharField(max_length=70)),
                ('Lastname', models.CharField(max_length=70)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.CharField(max_length=20)),
                ('Country', django_countries.fields.CountryField(default='INDIA', max_length=2)),
                ('Address', models.TextField(blank=True)),
                ('PinCode', models.CharField(max_length=10)),
                ('Bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=150)),
                ('Cateogry', models.CharField(choices=[('Cloths', 'Cloths'), ('Appliances', 'Appliances'), ('Fitness', 'Fitness'), ('Fashions', 'Fashions'), ('Grocery', 'Grocery'), ('Accessories', 'Accessories'), ('Sports', 'Sports'), ('Cosmetic', 'Cosmetic'), ('Electronics', 'Electronics'), ('Toys', 'Toys'), ('HomeDecoretion', 'HomeDecoretion'), ('OfficeFuniture', 'OfficeFuniture')], default='Cloths', max_length=50)),
                ('Price', models.CharField(blank=True, max_length=20)),
                ('Discount', models.CharField(blank=True, max_length=20)),
                ('Quantity', models.IntegerField(default=1)),
                ('Color', models.CharField(max_length=10)),
                ('Size', models.CharField(max_length=150)),
                ('Small_Decription', models.TextField(blank=True, help_text='Describe product in 200 letters', max_length=200)),
                ('Main_Image', models.ImageField(default='none', upload_to='product/images')),
                ('image_2', models.ImageField(default='none', upload_to='product/images')),
                ('image_3', models.ImageField(default='none', upload_to='product/images')),
                ('image_4', models.ImageField(default='none', upload_to='product/images')),
                ('image_5', models.ImageField(default='none', upload_to='product/images')),
                ('Details', models.TextField(blank=True)),
                ('Seller_Address', models.CharField(max_length=200)),
                ('Seller_Email', models.EmailField(max_length=64)),
                ('Seller_Mobile', models.CharField(max_length=20)),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.sellerdetails')),
            ],
        ),
    ]
