# Generated by Django 4.1.4 on 2022-12-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsdetails',
            name='Cateogry',
            field=models.CharField(choices=[('Toys', 'Toys'), ('OfficeFuniture', 'OfficeFuniture'), ('Cosmetic', 'Cosmetic'), ('Grocery', 'Grocery'), ('Cloths', 'Cloths'), ('Appliances', 'Appliances'), ('Fashions', 'Fashions'), ('Accessories', 'Accessories'), ('Fitness', 'Fitness'), ('Sports', 'Sports'), ('Electronics', 'Electronics'), ('HomeDecoretion', 'HomeDecoretion')], default='Cloths', max_length=50),
        ),
    ]
