# Generated by Django 3.1.7 on 2021-06-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='SellerPhone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='productsdetails',
            name='Cateogry',
            field=models.CharField(choices=[('Fitness', 'Fitness'), ('Appliances', 'Appliances'), ('Cosmetic', 'Cosmetic'), ('Sports', 'Sports'), ('Accessories', 'Accessories'), ('OfficeFuniture', 'OfficeFuniture'), ('Grocery', 'Grocery'), ('Electronics', 'Electronics'), ('HomeDecoretion', 'HomeDecoretion'), ('Toys', 'Toys'), ('Cloths', 'Cloths'), ('Fashions', 'Fashions')], default='Cloths', max_length=50),
        ),
    ]
