# Generated by Django 3.1.7 on 2021-06-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210623_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Buyer',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='productsdetails',
            name='Cateogry',
            field=models.CharField(choices=[('Cloths', 'Cloths'), ('Toys', 'Toys'), ('Fitness', 'Fitness'), ('Cosmetic', 'Cosmetic'), ('Appliances', 'Appliances'), ('Grocery', 'Grocery'), ('OfficeFuniture', 'OfficeFuniture'), ('HomeDecoretion', 'HomeDecoretion'), ('Accessories', 'Accessories'), ('Electronics', 'Electronics'), ('Sports', 'Sports'), ('Fashions', 'Fashions')], default='Cloths', max_length=50),
        ),
    ]
