# Generated by Django 4.1.4 on 2022-12-10 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerDetails',
            fields=[
                ('Profile_Pic', models.ImageField(default=None, upload_to='Seller_Profile_Pics')),
                ('Seller', models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Email', models.EmailField(default='', max_length=84)),
                ('Mobile_Number', models.CharField(max_length=20)),
                ('Country', django_countries.fields.CountryField(default='INDIA', max_length=2)),
                ('State', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('PinCode', models.CharField(max_length=10)),
                ('ShopAddress', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SellerReq',
            fields=[
                ('Seller_Name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Email', models.EmailField(default='', max_length=84)),
                ('Mobile', models.CharField(max_length=50)),
                ('Massage', models.TextField(max_length=200)),
                ('Product_Type', models.CharField(choices=[('Accessories', 'Accessories'), ('Appliances', 'Appliances'), ('Cloths', 'Cloths'), ('Cosmetic', 'Cosmetic'), ('Electronics', 'Electronics'), ('Fashions', 'Fashions'), ('Fitness', 'Fitness'), ('Grocery', 'Grocery'), ('HomeDecoretion', 'HomeDecoretion'), ('OfficeFuniture', 'OfficeFuniture'), ('Sports', 'Sports'), ('Toys', 'Toys')], default='Cloths', max_length=20)),
            ],
        ),
    ]
